import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <header className="header">
<<<<<<< HEAD
<<<<<<< HEAD
          <h1>המתכונים שלי</h1>
          <nav>
=======
          <h1 className="logo">המתכונים שלי</h1>
          <nav className="nav">
>>>>>>> e502f41 (add recipes cards)
            <Link className="nav-link" href="/recipes"></Link>
          </nav>
=======
        <h1>המתכונים שלי</h1>

>>>>>>> d5c1b8823ee113a28075c99f068300d0c7f101f2
        </header>
        <main>{children}</main> {/* This renders each page's content */}
      </body>
    </html>
  );
}
